title: "Saqib Nazir"
author: "Raheel Nazir"
description: "Expected Graduation: May 2027"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
# - {title: "CV", url: "/assets/Resume4%20-%20Raheel%20Nazir.pdf"}
# - {title: "Projects", file: "projects.md"}
# - {title: "Academics", file: "academics.md"}
# - {title: "About", file: "about.md"}
# - {title: "Contact", file: "contact.md"}


external:                  
  - {title: Mail, icon: envelope, url: "mailto:raheeelnazir@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/RaheelN2005"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/raheel-n-a6a14932a/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
